m6/MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from blog import views
from MyBlog import settings
from django.views.static import serve
from blog.ClassViews import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('index/', views.index),
    path('logout/', views.logout),
    path('comment/', views.comment),
    path('get_comment_tree/', views.get_comment_tree),
    path('backend/', views.backend),
    path('add_article/', views.add_article),
    path('get_validCode_img/', views.get_valid_code_img),
    path('upload/', views.upload),
    path('my_views', my_views.as_view()),

    # 以^开头，就表示以根路径开头，分组后，就会得到用户输入的内容，存储到别名username上
    re_path('^(?P<username>\w+)/$', views.home_site),
    re_path('^$', views.index),
    path('register/', views.register),
    re_path('^(?P<username>\w+)/article/(?P<article_id>\d+)/$',views.article_detail),

    # (?P<path>.*)分组后起别名path+固定格式
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^(?P<username>\w+)/(?P<condition>tag|category|archive)/(?P<param>.*)$', views.home_site)
]

m6/MyBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from blog.My_field import *


# 用户信息表。继承的AbstractUser类，本身就已经包含了username、password、email等字段，再额外的添加一些自定义的字段，实现自定义用户表，作为用户的接口表
class UserInfo(AbstractUser):
    nid=models.AutoField(primary_key=True)
    phone_list = (
        ('18611223344', 'wangxin de phone'),
        ('13911223344', 'who de phone'),
    )
    telephone=models.CharField(max_length=11,null=True,unique=True,choices=phone_list)
    avatar=models.FileField(upload_to='avatars/', default='/avatars/default.png')
    # verbose_name指明一个易于理解和表述的对象名称, /vɝ'bos/  冗长的；啰嗦的
    create_time=models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 与Blog表是一对一的关系，一对一关系在哪张表中建立关系都是可以的，看更倾向于通过哪张表作为源头去查找
    blog=models.OneToOneField(to='Blog',to_field='nid',null=True,on_delete=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    # 博客信息表也是站点表，一个用户对应一个博客，这三个属性也可以放在用户表中，但是为了解耦，可以单独存放
    nid=models.AutoField(primary_key=True)
    title=models.CharField(verbose_name='个人博客标题',max_length=64)
    site_name=models.CharField(verbose_name='站点名称',max_length=64)
    theme=models.CharField(verbose_name='博客主题',max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    # 文章分类表
    # 一个用户对应一个站点，因为一个用户对应多个分类，所以一个站点也是对应多个分类
    nid=models.AutoField(primary_key=True)
    title=models.CharField(verbose_name='分类标题',max_length=32)
    # 根据用户表去查找站点表和分类表的关系，一个用户对应多个分类，用户和站点是一对一的关系，所以要创建站点和分类的关系也是一对多关系，在多的表中创建外键
    blog=models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid=models.AutoField(primary_key=True)
    title=models.CharField(verbose_name='标签名称',max_length=32)
    blog=models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    # 基础字段
    nid=models.AutoField(primary_key=True)
    title=models.CharField(verbose_name='文章标题',max_length=50)
    desc=models.CharField(verbose_name='文章描述',max_length=255)
    create_time=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    content=models.TextField(verbose_name='文章详情')

    # 增加三个字段，用来存储评论数、点赞数和踩赞数。以后在查询某篇文章的评论数时，就会涉及到跨表查询，相比于添加操作和查询操作，跨表查询的效率会很低，所以每有一个新评论时，就在文章表中评论数列中+1
    comment_count=models.IntegerField(default=0)
    up_count=models.IntegerField(default=0)
    down_count=models.IntegerField(default=0)

    # 与用户的关系，一个用户对应多篇文章，一篇文章对应一个用户，多对多关系在多的表中创建关系
    user=models.ForeignKey(verbose_name='作者',to='UserInfo',to_field='nid',null=True,on_delete=True)
    # 与分类的关系，一个分类对应多篇文章，一篇文章对应一个分类
    category=models.ForeignKey(to='Category',to_field='nid',null=True,on_delete=True)
    # 与标签的关系，一个标签对应多篇文章，一篇文章对应多个标签
    tags=models.ManyToManyField(
        to='Tag',
        # 中间模型，不自动生成多对多关系表，使用手动创建的关系表
        through='Article2Tag',
        # 设置多对多的关系列，article列和tag列相互约束
        through_fields=('article','tag')
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid=models.AutoField(primary_key=True)
    article=models.ForeignKey(to='Article', to_field='nid', on_delete=True)
    tag=models.ForeignKey(to='Tag', to_field='nid', on_delete=True)

    class Meta:
        # 固定的联合为一列表变量名
        unique_together = [
            # 联合唯一，一篇文章不能对应重复标签
            ('article','tag')
        ]

    def __str__(self):
        # 返回article对象的title属性
        return self.article.title+'--'+self.tag.title


class ArticleUpDown(models.Model):
    nid=models.AutoField(primary_key=True)
    user=models.ForeignKey(to='UserInfo',to_field='nid',null=True,on_delete=True)
    article=models.ForeignKey(to='Article',to_field='nid',null=True,on_delete=True)
    is_up=models.BooleanField(default=True)

    class Meta:
        unique_together=[
            # 联合唯一，不允许同一用户对同一篇文章重复点赞
            ('user','article'),
        ]


class Comment(models.Model):
    # 基础字段
    nid=models.AutoField(primary_key=True)
    user=models.ForeignKey(to='UserInfo',to_field='nid',on_delete=True)
    article=models.ForeignKey(to='Article',to_field='nid',on_delete=True)
    create_time=models.DateTimeField(verbose_name='评论时间',auto_now_add=True)
    content=models.CharField(verbose_name='评论内容',null=True,max_length=255)

    # 如果只定义基础字段存储每一条评论，那么当有子级评论时，就无法确定父级评论是谁，所以添加parent_comment字段存储父级字段，为了起到约束的作用，使用ForeignKey，对于子级表中的字段，可以使用Comment，也可以是self，null=True表示评论为根评论，也是就是对文章的评论，而不是对评论的评论
    parent_comment=models.ForeignKey('self',null=True,on_delete=True)

    def __str__(self):
        return self.content


class ListTest(models.Model):
    label = ListField()

    def __str__(self):
        return '%s'%self.label

m6/MyBlog/templates/add_article.html
{% extends 'base_platform.html' %}
{% block blog-title %}
    <a href="/backend/">后台管理</a>
{% endblock %}

{% block category %}
    <div class="panel panel-warning">
        <div class="panel-heading">后台操作</div>
        <div class="panel-body">
            <div>
                <a href="/add_article/">添加新文章</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block article_info %}
    <form action="" method="post" style="margin-top: 30px">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">标题</label>
            <input type="text" id="title" name="article-title" class="form-control">
        </div>
        <div class="form-group">
            <div>
                <label for="">请选择分类</label>
            </div>
            <select class="form-control" name="category">
                {% for cate in cate_list %}
                    <option value="{{ cate.nid }}">{{ cate.title }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <div>
                <label for="">请选择标签(按住Ctrl键多选)</label>
            </div>
            <select multiple class="form-control" name="tag">
                {% for tag in tag_list %}
                    <option value="{{ tag.nid }}">{{ tag.title }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="">文章详情</label>
            <textarea id="editor_id" cols="30" name="article-content" rows="10" class="form-control"></textarea>
        </div>
        <div class="commit-btn">
            <input type="submit" class="btn btn-success">
        </div>
    </form>
    <script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/jquery/jquery-3.3.1.js"></script>
    <script charset="utf-8" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#editor_id', {
                width: '100%',
                height: '500px',
                items: [
                    'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
                    'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
                    'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
                    'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
                    'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                    'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
                    'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
                    'anchor', 'link', 'unlink', '|', 'about'
                ],
                uploadJson:'/upload/',
                extraFileUploadParams:{
                    'csrfmiddlewaretoken':$('[name="csrfmiddlewaretoken"]').val()
                },
                filePostName:'upload_img',
            });
        });
    </script>
{% endblock %}

m6/MyBlog/templates/article_detail.html
{% extends 'base_platform.html' %}
{% block blog-title %}
    <a href="/{{ username }}">{{ blog.title }}</a>
{% endblock %}
{% block category %}
    {% load my_filter %}
    {% get_classification username %}
{% endblock %}
{% block article_info %}
    {% csrf_token %}
    <div class="article_top">
        <div class="article_count">
            随笔-133&nbsp&nbsp文章-160&nbsp&nbsp评论-500
        </div>
        <div class="title">
            <a href="">{{ article_obj.title }}</a>
        </div>
    </div>
    <div class="content">
        {{ article_obj.content | safe }}
    </div>
    <div class="digg-box">
        <div id="div_digg">
            <div class="diggit">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>
            <div class="buryit">
                <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red;"></div>
        </div>
    </div>
{% endblock %}
{% block comment_info %}
    <div class="comment-area">
            <div class="comment-tree">
                评论树
                <div class="comment-item" comment_id="">

                </div>
            </div>
            {% if comment_obj %}
                <div class="comment-list">
                    评论列表
                </div>
                {% for comment in comment_obj %}
                    <div class="main">
                    <div class="comment-item">
                        <div class="floor-info">
                            <div class="comment-info">
                                #<span>{{ forloop.counter }}</span>楼
                                <a name="{{ comment.pk }}"></a>
                                <span>{{ comment.create_time | date:'Y-m-d H:i:s' }}</span>
                                <span><a href="/{{ comment.user.username }}">{{ comment.user.username }}</a></span>
                            </div>
                            <div class="edit-comment">
                                <a href="">修改</a>
                                <a href="">删除</a>
                            </div>
                        </div>
                    </div>
                    <div class="comment-content">
                        {% if comment.parent_comment %}
                            <div class="parent-info">
                                <a href="#{{ comment.parent_comment_id }}">@</a>
                                <span>{{ comment.user.username }}</span>
                            </div>
                        {% endif %}
                        {{ comment.content }}
                        <div class="anwser" comment_id="{{ comment.pk }}">
                            回复
                        </div>
                        <div class="digg_bury">
                            <a href="">支持</a>
                            <a href="">反对</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}


        <div class="article-comment">
            <div class="comment-btn">
                <ul>
                    <li><a href="">刷新评论</a></li>
                    <li><a href="">刷新页面</a></li>
                    <li><a href="">返回顶部</a></li>
                </ul>
            </div>
            <div class="comment-title">
                <img src="/static/img/icon_addcomment.gif" alt="">
                <p>发表评论</p>
            </div>
            <div class="comment-box">
                <div class="comment-peo">
                    <label style="color: darkgrey;font-size: 16px" for="">昵称：</label>
                    <input class="current_user" type="text" value="{{ request.user.username }}" disabled>
                </div>
                <div class="conment-content">
                    <div>
                        <label style="color: darkgrey;font-size: 16px" for="">评论内容：</label>
                    </div>
                    <textarea name="" id="comment-text" cols="80" rows="10"></textarea>
                </div>
                <button class="btn btn-success commit-btn">提交评论</button>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            // 设置parent_pid默认为空，就是根评论，只有点击了回复按钮后，才会对该变量重新赋值，变为当前评论的主键值
            var parent_pid = ''
            $('.commit-btn').click(function () {
                var comment_content = $('.conment-content textarea').val()

                if(parent_pid){
                    var index = $('.conment-content textarea').val().indexOf('\n')
                    comment_content = $('.conment-content textarea').val().slice(index+1,)
                }

                $.ajax({
                    url: '/comment/',
                    type: 'post',
                    data: {
                        "article_id": '{{ article_obj.pk }}',
                        'comment_content': comment_content,
                        'parent_pid': parent_pid,
                        'csrfmiddlewaretoken': $('[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (data) {
                        var s = `<div class="dis-comment">
                                    <div class="new-comment">
                                        <img src="/static/img/icon_comment.gif" alt="">
                                        <p id="peo">
                                            <span class="comment-person">{{ request.user.username }}</span>
                                            <span class="comment-time">${data.create_time}</span>
                                        </p>
                                    </div>
                                    <div class="new-comment-content">${data.comment_content}</div>
                                </div>`
                        console.log(data);
                        //提交子评论后，parent_pid的值变为父评论的pk值，导致再次提交评论时，还是带有父评论的，所以执行清空操作
                        parent_pid = ''
                        // 点击提交按钮后，将已评论的内容清空
                        $('#comment-text').val('')
                        $('.article-comment').before(s)
                    }
                })
            })

            $('.anwser').click(function(){
                parent_pid = $(this).attr('comment_id')
                // 我是通过DOM导航查找到了用户名，但是可以自定义属性，如在回复所在的a标签添加自定义属性username=当前登录用户
                var target_user = $(this).parent().siblings('.comment-item').children().children('.comment-info').children()[3].innerText
                // focus不仅会实现光标选中，而且会跳转到目标控件位置
                $('#comment-text').text('@'+target_user+'\n').focus()
            })

            $('.comment-tree').click(function(){
                $.ajax({
                    url:'/get_comment_tree/',
                    type:'get',
                    data:{
                        'article_id': '{{ article_obj.pk }}',
                    },
                    success:function(data){
                        console.log(data)
                        $.each(data, function(index, value){
                            var s = `<div class="comment-item" comment_id="${value.pk}">${value.content}</div>`

                            if(!value.parent_comment){
                                $('.comment-tree').append(s)
                            }else{
                                console.log(123)
                                var parent_comment = value.parent_comment
                                $('[comment_id='+parent_comment+']').append(s)
                            }
                        })
                    }
                })
            })
        })
    </script>
{% endblock %}

m6/MyBlog/templates/backend_manage.html
{% extends 'base_platform.html' %}

{% block blog-title %}
    <a href="/backend/">后台管理</a>
{% endblock %}

{% block category %}
    <div class="panel panel-warning">
        <div class="panel-heading">后台操作</div>
        <div class="panel-body">
            <div>
                <a href="/add_article/">添加新文章</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block article_info %}
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="#">文章</a></li>
      <li role="presentation"><a href="#">日期</a></li>
      <li role="presentation"><a href="#">随笔</a></li>
    </ul>
    <div class="artile-list">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>文章标题</th>
                    <th>发布时间</th>
                    <th>评论数</th>
                    <th>点赞数</th>
                    <th>操作</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for article in article_list %}
                    <tr>
                        <td><a href="">{{ forloop.counter }}</a></td>
                        <td><a href="">{{ article.title }}</a></td>
                        <td>{{ article.create_time | date:'Y-m-d H:i:s' }}</td>
                        <td>{{ article.comment_count }}</td>
                        <td>{{ article.up_count }}</td>
                        <td><a href="">编辑</a></td>
                        <td><a href="">删除</a></td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

m6/MyBlog/templates/base_platform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/article_detail.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <script type="text/javascript" src="/static/jquery/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/recommend.js"></script>
</head>
<body>
    <div class="nav-top">
        <div class="blog-title">
            {% block blog-title %}
{#                <a href="">后台管理</a>#}
                <a href="">小蝌蚪</a>
            {% endblock %}
        </div>
        <div class="nav-btn">
            {% if request.user.username == username %}
                <a href="/backend/" id="backend-manage">管理</a>
                <a href="/">首页</a>
            {% else %}
                <a href="/{{ request.user.username }}/">我的博客</a>
            {% endif %}
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% block category %}

                {% endblock %}
            </div>
            <div class="col-md-9 ">
                {% block article_info %}

                {% endblock %}

                {% block comment_info %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>
<script type="text/javascript">
    $('#backend-manage').click(function(){

    })
</script>
</html>

m6/MyBlog/templates/cate_style.html
<div class="panel panel-info">
    <div class="panel-heading">我的标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <div>
                <a href="/{{ username }}/tag/{{ tag.title }}">{{ tag.title }}({{ tag.article_count }})</a>
            </div>
        {% endfor %}
    </div>
</div>
<div class="panel panel-warning">
    <div class="panel-heading">随笔分类</div>
    <div class="panel-body">
        {% for cate in cate_list %}
            <div>
                <a href="/{{ username }}/category/{{ cate.title }}">{{ cate.title }}({{ cate.article_count }})</a>
            </div>
        {% endfor %}
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">随笔档案</div>
    <div class="panel-body">
        {% for date in date_list_2 %}
            <div>
                <a href="/{{ username }}/archive/{{ date.month | date:'Y' }}/{{ date.month | date:'m' }}">{{ date.month | date:'Y-m' }}({{ date.article_count }})</a>
            </div>
        {% endfor %}
    </div>
</div>

m6/MyBlog/templates/home_site.html
{% extends 'base_platform.html' %}
{% block blog-title %}
{#    <a href="/{{ username }}">{{ blog.title }}</a>#}
    {{ block.super }}
{% endblock %}
{% block category %}
    {% load my_filter %}
    {% get_classification username %}
{% endblock %}
{% block article_info %}
    {% for article in article_list %}
        <div class="article-item">
            <h5><a href="/{{ username }}/article/{{ article.nid }}">{{ article.title }}</a></h5>
            <div class="article-desc media-right">
                <span>{{ article.desc }}</span>
            </div>
            <div class="article-info small">
                <span>
                    发布于&nbsp{{ article.create_time | date:'Y-m-d H:i:s' }}
                    <span style="color: #0f0f0f">{{ user.get_telephone_display }}{{ user.telephone }}</span>
                    <span>
                        <img src="/static/img/icon_comment.gif" alt="">
                        <a href="">评论({{ article.comment_count }})</a>
                    </span>
                    <span>
                        <img src="/static/img/icon_arrow.gif" alt="">
                        <a href="">点赞({{ article.up_count }})</a>
                    </span>
                </span>
            </div>
        </div>
        <hr>
    {% endfor %}
{% endblock %}

m6/MyBlog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客园</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <script type="text/javascript" src="/static/jquery/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
    <style type="text/css">
        .glyphicon {
        {#设置元素的垂直对齐方式，上下适当调整位置#} vertical-align: -1px;
        }
        .article-info{
            margin-top: 10px;
        }
        .article-info a{
            text-decoration: none;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">文章</a></li>
                <li><a href="#">博客</a></li>
                <li><a href="#">随笔</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-user"></span>
                            {{ request.user.username }}
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">我的<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">修改头像</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="article_list">
                {% for article in article_list %}
                    <div class="article-item">
                        <h5><a href="{{ article.user.username }}/article/{{ article.pk }}">{{ article.title }}</a></h5>
                        <div class="user-avatar media-left">
                            <img width="65" height="65" src="/media/{{ article.user.avatar }}" alt="">
                        </div>
                        <div class="article-desc media-right">
                            <span>{{ article.desc }}</span>
                        </div>
                        <div class="article-info small">
                            <span>
                                <a href="/{{ article.user.username }}/">{{ article.user.username }}</a>
                                发布于&nbsp{{ article.create_time | date:'Y-m-d H:i:s' }}
                                <span>
                                    <img src="/static/img/icon_comment.gif" alt="">
                                    <a href="">评论({{ article.comment_count }})</a>

                                </span>
                                <span>
                                    <img src="/static/img/icon_arrow.gif" alt="">
                                    <a href="">点赞({{ article.up_count }})</a>
                                </span>
                            </span>
                        </div>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-success">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

m6/MyBlog/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
</head>
<body>
    <h3>登录</h3>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">用户名</label>
                    <input type="text" class="form-control" name="username">
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="form-group">
                    <label for="">验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="valid_code">
                        </div>
                        <div class="col-md-6">
                            <img width="270" height="40" src="/get_validCode_img/" alt="" id="valid_code">
                        </div>
                    </div>
                </div>
                <button class="btn btn-default login-btn">登录</button>
                <a href="/register" class="btn btn-success pull-right">注册</a>
                <span class="error"></span>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="/static/jquery/jquery-3.3.1.js"></script>
<script type="text/javascript">
    $(function(){
        $('#valid_code').click(function(){
            <!--对于图片的src链接，如果想点击后刷新图片，再次请求，那么就对src链接内容+='?'一个问号即可-->
            $(this)[0].src+='?'
        })

        $('.login-btn').click(function(){
            $.ajax({
                // 如果没有填写ajax的请求路径，那么就是当前路径
                url:'',
                type:'post',
                data: {
                    'username':$('[name="username"]').val(),
                    'password':$('[name="password"]').val(),
                    'valid_code':$('[name="valid_code"]').val(),
                    'csrfmiddlewaretoken':$('[name="csrfmiddlewaretoken"]').val()
                },
                success:function(data){
                    if(data.user){
                        // 如果校验验证码、用户名和密码成功后，则跳转至index页面
                        location.href='/index'
                    }else{
                        $('.error').text(data.msg)
                        $('.error').css({'color':'red','margin-left':'10px'})

                        setTimeout(function(){
                            $('.error').text('')
                        },2000)
                    }
                }
            })
        })
    })
</script>
</html>